server:  
  port: 9001

eureka: 
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8001}/eureka/
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2 
