info:
  component: Gateway
  
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    port: 8001
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8001}/eureka/
  server:
wait-time-in-ms-when-sync-empty: 3000

zuul:
   prefix: /api
   routes:
      order:
        path: /project-order-service/**
        serviceId: project-order-service
      feigOrder:
        path: /project-feign-service/**
        serviceId: project-feign-service

project-order-service:
  ribbon:
    eureka:
      enabled: true
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
    ServerListRefreshInterval: 60000
    DeploymentContextBasedVipAddresses: project-order-service
    NIWSServerListFilterClassName: com.netflix.loadbalancer.ServerListSubsetFilter
    ServerListSubsetFilter:
size: 5 
